FROM node:16.14

RUN mkdir /app

WORKDIR /app

COPY package.json /app/package.json

RUN npm install

COPY . /app

EXPOSE 4200

CMD npm start
# COPY --from=build /app/dist/devops_exercise_2022_frontend /usr/share/nginx/html