# Angular
FROM node:latest as builder

WORKDIR /app

COPY package.json /app

RUN npm install && npm install -g @angular/cli@latest

COPY . /app

RUN npm run build

# Nginx
FROM nginx:latest

COPY --from=builder /app/dist/* /app

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80