# Angular
FROM node:latest as builder

WORKDIR /app
COPY . .

# IF DEV THEN WATCH / POLL ? ELSE 0.0.0.0
RUN npm install && \
    npm run build

# Nginx
FROM nginx:alpine
COPY --from=builder /app/dist/* /usr/share/nginx/html/
COPY /nginx.conf /etc/nginx/conf.d/default.conf