version: '3.9'

services:
    frontend:
        image: frontend
        container_name: frontend
        build:
            context: ./frontend
            target: dev
        volumes:
            - "/app/node_modules"
            - "./frontend:/app"
        depends_on:
            - api
        ports:
        - 4200:4200
        restart: on-failure
        
    api:
        build: 
            context: ./api
            dockerfile: Dockerfile.dev
        container_name: api
        hostname: api
        environment:
            - MONGO_URL=mongodb://root:example@database:27017
            - DB_NAME=devops_db
        volumes:
            - ./api:/app
        ports:
        - 3000:3000
    
    # poort vanaf buiten de docker-compose niet te benaderen?
    database:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
            MONGO_INITDB_DATABASE: devops_db
        volumes:
            - ./database/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro