name: Node.js CI
on:
  push:
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: ./api

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 16
          uses: actions/setup-node@v2
          with:
            node-version: '16'

        - name: Install CI
          run: npm ci

        - name: Run Jest
          uses: ArtiomTr/jest-coverage-report-action@v2
          with:
            working-directory: ../api

        - name: Run ESLint
          run: npm run lint