on:
  pull_request:
    branches:
      - main

name: deploy

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
   
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
   
    - uses: okteto/namespace@latest
   
    - name: "Create stack"
      uses: okteto/deploy-stack@latest
      with:
        build: "true"
