name: deploy
on:
  pull_request:
    branches:
      - main

jobs:
  devflow:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Set context to Okteto Cloud
          uses: okteto/context@latest
          with:
            token: ${{ secrets.OKTETO_TOKEN }}

        - uses: okteto/namespace@latest
        - name: "Create stack"
          uses: okteto/deploy-stack@latest
          with:
            build: "true"
